
blender_install_path: /Users/mikhailburakov/blender
sds_root_path: /Users/mikhailburakov/data/sds
target_dataset_name: itodd
distractor_dataset_name: tless
src_path: /Users/mikhailburakov/prog/sds
cc_textures_path: /Users/mikhailburakov/data/bproc/cc_textures
output_path: null
output_postfix: ''
images_per_dir: 1000


generation:
  room_size: 1.5
  scenes_num: 50
  depth_antialiasing: false
  render_samples: 10
  # render_samples: 50
  image_size: [1280, 960]
  scene:
    images_num: 20
    target_objects_num: 30
    distractor_objects_num: 10
    max_duplicate_objects: 3

